version: "3.5"

services:

  data-mesh-customer-api-1:
    image: trivadis/data-mesh-customer-api:latest
    hostname: data-mesh-customer-api-1
    container_name: data-mesh-customer-api-1
    labels:
      com.platys.restapi.title: 'data-mesh-customer-api-1'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48080"    
    expose:
      - 8081
    ports:
      - "48080:8081"
      
  data-mesh-salesorder-api-1:
    image: trivadis/data-mesh-salesorder-api:latest
    hostname: data-mesh-salesorder-api-1
    container_name: data-mesh-salesorder-api-1
    labels:
      com.platys.restapi.title: 'data-mesh-salesorder-api-1'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48081"    
    expose:
      - 8081
    ports:
      - "48081:8081"    
      
  data-mesh-salesorder-dp-1:
    image: trivadis/data-mesh-salesorder-dp:latest
    hostname: data-mesh-salesorder-dp-1
    container_name: data-mesh-salesorder-dp-1
    labels:
      com.platys.restapi.title: 'data-mesh-salesorder-dp-1'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48082"    
    expose:
      - 8080
    ports:
      - "48082:8080"              