--------------------------------------------------------
--  Create USER and Roles
--------------------------------------------------------

-- USER SQL
ALTER USER "PRODUCT"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "PRODUCT" DEFAULT ROLE "DBA","PPLB_ROLE","DV_MONITOR","CTXAPP","DV_AUDIT_CLEANUP","EM_EXPRESS_ALL","WM_ADMIN_ROLE","OLAP_USER","OLAP_XS_ADMIN","DV_SECANALYST","MAINTPLAN_APP","RECOVERY_CATALOG_OWNER_VPD","XS_CACHE_ADMIN","AVTUNE_PKG_ROLE","GDS_CATALOG_SELECT","SCHEDULER_ADMIN","PROVISIONER","AUDIT_ADMIN","XDB_WEBSERVICES_OVER_HTTP","AQ_ADMINISTRATOR_ROLE","SYSUMF_ROLE","APPLICATION_TRACE_VIEWER","XDB_WEBSERVICES","LBAC_DBA","OPTIMIZER_PROCESSING_RATE","RECOVERY_CATALOG_USER","DV_DATAPUMP_NETWORK_LINK","GSMUSER_ROLE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","DBJAVASCRIPT","GSM_POOLADMIN_ROLE","DV_ADMIN","DV_POLICY_OWNER","HS_ADMIN_ROLE","XS_SESSION_ADMIN","DV_GOLDENGATE_ADMIN","IMP_FULL_DATABASE","DV_XSTREAM_ADMIN","DV_PATCH_ADMIN","GGSYS_ROLE","DATAPUMP_EXP_FULL_DATABASE","EJBCLIENT","HS_ADMIN_EXECUTE_ROLE","JMXSERVER","OLAP_DBA","ADM_PARALLEL_EXECUTE_TASK","JAVAIDPRIV","SELECT_CATALOG_ROLE","JAVADEBUGPRIV","CONNECT","ACCHK_READ","DATAPUMP_IMP_FULL_DATABASE","SODA_APP","BDSQL_ADMIN","OEM_MONITOR","GSMADMIN_ROLE","AQ_USER_ROLE","JAVAUSERPRIV","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","JAVA_ADMIN","DBFS_ROLE","PDB_DBA","RDFCTX_ADMIN","DV_GOLDENGATE_REDO_ACCESS","CDB_DBA","JAVASYSPRIV","GSMROOTUSER_ROLE","HS_ADMIN_SELECT_ROLE","AUDIT_VIEWER","RESOURCE","DV_OWNER","XDB_WEBSERVICES_WITH_PUBLIC","EXECUTE_CATALOG_ROLE","DATAPATCH_ROLE","DV_ACCTMGR","EXP_FULL_DATABASE","DBMS_MDX_INTERNAL","DV_STREAMS_ADMIN","XS_NAMESPACE_ADMIN","BDSQL_USER","ORDADMIN","AUTHENTICATEDUSER","CAPTURE_ADMIN","OEM_ADVISOR","XS_CONNECT","XDBADMIN","EM_EXPRESS_BASIC";

-- SYSTEM PRIVILEGES


--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PRODUCT"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"PRODUCT_NUMBER" VARCHAR2(200 BYTE), 
	"COLOR" VARCHAR2(200 BYTE), 
	"STANDARD_COST" VARCHAR2(200 BYTE), 
	"LIST_PRICE" VARCHAR2(200 BYTE), 
	"SAFETY_STOCK_LEVEL" VARCHAR2(200 BYTE), 
	"MAKE_FLAG" VARCHAR2(200 BYTE), 
	"FINISHED_GOODS_FLAG" VARCHAR2(200 BYTE), 
	"MODIFIED_DATE" DATE, 
	"SELL_START_DATE" DATE, 
	"EVENT_TIMESTAMP" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRODUCT"."PRODUCT_PK" ON "PRODUCT"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


--------------------------------------------------------
--  PRODUCT TRUNCATE
--------------------------------------------------------
TRUNCATE TABLE "PRODUCT"."PRODUCT"
SELECT count(*) FROM "PRODUCT"."PRODUCT"

--------------------------------------------------------
--  PRODUCT in ORACLE
--------------------------------------------------------
JDBC Connection String: jdbc:oracle:thin:@18.184.160.165:1522/XEPDB1
Schema Name:    PRODUCT
Table Name      PRODUCT
Username:       PRODUCT
Password:       abc