---
security:
  auth:
    token:
      # given a SSO environment Optimize's own sessions can be short lived
      lifeMin: 1

plugin:
  authenticationExtractor:
    basePackages: ['org.camunda.optimize.examples']

ui:
  logoutHidden: true
